### ISSUE TITLE
Possible source for the clipboard image insertion

### ISSUE THREAD

**Issue by nerdvarma** [nobiot/Zero-to-Emacs-and-Org-roam#14]
I've also been using a similar process for inserting clipboard images into org files, and this is where I found it.
https://www.sastibe.de/2018/11/take-screenshots-straight-into-org-files-in-emacs-on-win10/
Might have been the same place you also came across it.
(Hope this isn't rude or anything. This is the first github issue I have raised.)

**Comment by nobiot** [comment]
Oh, thank you! No, not rude at all.
I think this site might have been the one, but I don't really remember.  
I will put it in as a reference any way.
Thanks again :)

**Comment by nobiot** [comment]
Added the reference you pointed out as a footnote. Thank you.
I vaguely remember the image from that article, so I am sure I used it (I think there was another one from Stack Exchange too, but I don't now).
