### ISSUE TITLE
Windows 11: No EmacSQL SQLite binary available, aborting

### ISSUE THREAD

**Issue by ghowoo** [nobiot/Zero-to-Emacs-and-Org-roam#19]
Roam is a very promising tool and I have followed the instructions to set up org roam on Windows. However, it still doesn't work. When I "C-c n l" to open a new org file, it just says "No EmacSQL SQLite binary available, aborting".

I did install gcc through msys64 and install sqlite3 and put them in the path. Any insights will be helpful if I should go to modify the roam .el file.

**Comment by nobiot** [comment]
Three things to begin with. 

1. I don’t know Windows 11. All I did is for Windows 10. I can only hope and assume that there is no or immaterial differences

2.  I don’t know what is msys64. I installed msys2. What did you install and how?

3. What did you put in the path? Can you run cmd to open the command line prompt and then call gcc and sqlite3 inside the command line prompt? If you can’t, then the path is not correctly set

**Comment by nobiot** [comment]
One more thing. What Is roam.el?

**Comment by ghowoo** [comment]
Thanks nobiot. 
You are very helpful. The problem has been solved.

I had installed msys2 64, not msys64. Sorry for the confusion, however, the default folder name is msys64. But I didn't set C:\msys64\user\bin to the path. After I set the path, roam works.

Great work!

**Comment by nobiot** [comment]
Good to know that Windows 11 also works.
Thank you.
