### ISSUE TITLE
It seems Firefox with old version of org also require the patch for org-protocol

### ISSUE THREAD

**Issue by pRot0ta1p** [nobiot/Zero-to-Emacs-and-Org-roam#4]
Runing Msys2 version of Emacs 26.3 Org version 9.19, and Firefox 79.0, clicking on the org-roam graph will throw up a blank file.

The patch for Chrome (https://github.com/nobiot/Zero-to-Emacs-and-Org-roam/blob/main/90.org-protocol.md#chrome-only-patch-org-mode-for-org-protocol-and-org-roam-protocol) can solve this issue.

**Comment by nobiot** [comment]
@pRot0ta1p thanks!

This might be because your Org version is a bit old? 
I'm on Firefox 79.0 as well, but the Org version I used to write this chapter was 9.3.6.

Is it possible for you to upgrade your Org?
If not, I'll note this somewhere in the chapter.

**Comment by pRot0ta1p** [comment]
Yes, I can confirm upgrade to org latest tag 9.3.7 can also resolve the problem. 
So its probably a issue of old org, considering this version of org shipped with 
current stable emacs, maybe its worth a note in this tutor?

**Comment by nobiot** [comment]
Thank you. Sure, will add a note.

**Comment by nobiot** [comment]
Thanks for adding the detail. Let me know if you have a better suggestion.
