### ISSUE TITLE
30.Set-up-Org-roam.md - Reference to M-h e

### ISSUE THREAD

**Issue by pajot** [nobiot/Zero-to-Emacs-and-Org-roam#7]
In the section Set-up Org-roam, there is this line:

> Now you can save this. Let's quit Emacs and relaunch it. Once you see the start screen, invoke M-h e to view "echo message." Do you notice the two files and one link you created earlier have been added to Org-roam's database?

By default, M-h is bound to mark-paragraph, so "M-h e" just types 'e' into the active buffer.
![Screenshot_20201217_162421](https://user-images.githubusercontent.com/4051461/102507523-a7cca700-4084-11eb-9d3e-fe7e045ee35f.png)
Another custom configuration I've missed, perhaps?

**Comment by nobiot** [comment]
oh thanks! no you didn't miss anything. it's me. it should be C-h e, not M-h e. I'll fix this. thank you for pointing it out.

**Comment by nobiot** [comment]
#9 fixes this incorrect reference. Thank you for the PR.
